### PR TITLE
PR: Initial implementation

### PR DESCRIPTION
**Pull request by LuchoTurtle**
This is the PR for the initial implementation of this tutorial and feature. So far it's still a *work-in-progress* and there are some features that I'd like to add such as:
- different colors between cursors for each user
- interaction between each user (below cursor)
- fixing CSS overflow concerns.

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
@nelsonic here's the fully tested and with the README completed version of the project. Let me know if anything's missing :smile:

**Comment by nelsonic** [comment]
@LuchoTurtle sorry I didn't get to this sooner. ⏳ 
Please **_assign_ PRs** to me when ready `else` I don't get notified ... 👤 
I know the UI/UX of GitHub is confusing with the "Request review" interface/action. 🙄 
But given how many notifications I get per day, 📥 
the only one I look at for "unblocking" or reviewing PRs is: [github.com/**pulls/assigned**](https://github.com/pulls?q=is%3Aopen+is%3Apr+assignee%3ANelsonic) 🔔 
I know it might feel like "process" (bordering on bureaucracy...), 
but for us the **`in-progress`** label  means "_still **being worked on** by the **assignee**_" 👨‍💻 
whereas **`awaiting-review`** - no surprises - means "_**awaiting review** of the person it's **assigned** to_". 🙏 
Our aim is to completely _streamline_ these types of interactions in our **`App`**. 📱 
GitHub is a bit of a Frankenstein's Monster when it comes to ["workflow"](https://github.com/dwyl/contributing/issues/109) ... 🤷‍♂️ 

Anyway, looking at this now. 👌

**Comment by nelsonic** [comment]
Dunno if you saw this while you were doing your pre-review: 💭 

image

image

Going to take a look at resolving it now. 👨‍💻 ⏳

**Comment by nelsonic** [comment]
Luckily someone `else` has seen this and took the time to open this ElixirForum Post:
https://elixirforum.com/t/liveview-session-was-misconfigured-or-the-user-token-is-outdated/32219/2
image

Simple fix. ✅

**Comment by nelsonic** [comment]
Works well on `localhost`: 🎉 

cursor-tracking-demo-GIF

Going to deploy to fly.io for live demo. 🤞

**Comment by nelsonic** [comment]
https://live-cursors.fly.dev 🚀

**Comment by nelsonic** [comment]
Enabled auto-deploys via `ci.yml`

**Comment by nelsonic** [comment]
Next, Please see: https://github.com/dwyl/mvp/issues/190 🙏

**Pull request merged**
